name: CI-CD

#event que vai ser disparado para iniciar a automação : on
on:
  #envia para branch
  push:
    branches: ["main"]
  #permite executar de forma manual
  workflow_dispatch:
#sequenias de etapas 
jobs:
  #CI/CD simples, então declara no mesmo wokrflow, cria dois jobs
  ci:
    #agente de executacao, em qual ambiente
    runs-on: ubuntu-latest
    #passos de executação da pipeline
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4
      -
        name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Construção da imagem Docker
        run: echo "Executando o comando Docker Build"
      - name: Envio da imagem Docker
        run: echo "Eecutando o comando Docker push"

  cd:
    #agente de executacao, em qual ambiente
    runs-on: ubuntu-latest
    #depende do job CI, executa depois do CI
    needs: [ci]
    #passos de executação da pipeline
    steps:
      - name: Autenticar na AWS
        run: echo "Executando o comando aws configure"
      - name: Construção o Kubectl
        run: echo "Executando o comando aws eks update-kubeconfig"
      - name: Deploy dos manifestos no Kubernets
        run: echo "Eecutando o comando kubectl apply"
